apiVersion: backstage.io/v1alpha1
kind: Component
metadata:
  name: emoodji
  description: Emoodji
  tags:
  - app-accelerator
  - java
  - spring
  - web
  - tanzu
  annotations:
    backstage.io/kubernetes-label-selector: app.kubernetes.io/part-of=emoodji
spec:
  type: service
  lifecycle: experimental
  owner: default-team
