apiVersion: carto.run/v1alpha1
kind: Workload
metadata:
  name: emoodji
  labels:
    apps.tanzu.vmware.com/workload-type: web
    apps.tanzu.vmware.com/has-tests: "true"
    apis.apps.tanzu.vmware.com/register-api: "true"
    app.kubernetes.io/part-of: emoodji
spec:
  source:
    git:
      url: https://github.com/alexandreroman/emoodji
      ref:
        branch: testing
  params:
  - name: annotations
    value:
      autoscaling.knative.dev/minScale: "0"
  - name: testing_pipeline_matching_labels
    value:
      apps.tanzu.vmware.com/pipeline: test
      apps.tanzu.vmware.com/language: java
  - name: api_descriptor
    value:
      type: openapi
      location:
        path: /v3/api-docs
      owner: default-team
      system: emoodji
      description: Emoodji API
  build:
    env:
    - name: BP_JVM_VERSION
      value: "17"
