apiVersion: carto.run/v1alpha1
kind: Workload
metadata:
  name: emoodji
  labels:
    apps.tanzu.vmware.com/workload-type: web
    apps.tanzu.vmware.com/has-tests: "true"
    app.kubernetes.io/part-of: emoodji
spec:
  source:
    git:
      url: https://github.com/alexandreroman/emoodji
      ref:
        branch: testing
  params:
  - name: annotations
    value:
      autoscaling.knative.dev/minScale: "0"
  - name: testing_pipeline_matching_labels
    value:
      apps.tanzu.vmware.com/pipeline: test
      apps.tanzu.vmware.com/language: java
  build:
    env:
    - name: BP_JVM_VERSION
      value: "17"
  env:
  - name: APP_TITLE
    value: Emoodji with PostgreSQL
  - name: SPRING_PROFILES_ACTIVE
    value: postgres
  serviceClaims:
  - name: db
    ref:
      apiVersion: services.apps.tanzu.vmware.com/v1alpha1
      kind: ResourceClaim
      name: emoodji-db-postgres-claim
